### ISSUE TITLE
Add test info to setup.py

### ISSUE THREAD

**Issue by john-sandall** [john-sandall/maven#10]
Add [test info to setup.py](https://python-packaging.readthedocs.io/en/latest/testing.html)

**Comment by joy-rosie** [comment]
@john-sandall, @cruzzoe and I have created a pull request for this https://github.com/john-sandall/maven/pull/13. 

Please review and let us know if it's what you were looking for.

**Comment by john-sandall** [comment]
Closed by #13

**Comment by john-sandall** [comment]
@joy-rosie @cruzzoe I've added you both to [AUTHORS.md](https://github.com/john-sandall/maven/blob/master/AUTHORS.md). Let me know if you'd like me to remove you, or if you'd like me to add additional information (e.g. name or email).

Thanks again!
